services:
  acount_service:
    build:
      context: ./account_service
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    #volumes:
    #  - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
